- name: "component / contrib.admin"
  color: "5319E7"
- name: "component / contrib.admindocs"
  color: "5319E7"
- name: "component / contrib.auth"
  color: "5319E7"
- name: "component / contrib.contenttypes"
  color: "5319E7"
- name: "component / contrib.flatpages"
  color: "5319E7"
- name: "component / contrib.humanize"
  color: "5319E7"
- name: "component / contrib.messages"
  color: "5319E7"
- name: "component / contrib.postgres"
  color: "5319E7"
- name: "component / contrib.redirects"
  color: "5319E7"
- name: "component / contrib.sessions"
  color: "5319E7"
- name: "component / contrib.sitemaps"
  color: "5319E7"
- name: "component / contrib.sites"
  color: "5319E7"
- name: "component / contrib.staticfiles"
  color: "5319E7"
- name: "component / contrib.syndication"
  color: "5319E7"
- name: "component / Core (Cache system)"
  color: "5319E7"
- name: "component / Core (Mail)"
  color: "5319E7"
- name: "component / Core (Management commands)"
  color: "5319E7"
- name: "component / Core (Other)"
  color: "5319E7"
- name: "component / Core (Serialization)"
  color: "5319E7"
- name: "component / Core (System checks)"
  color: "5319E7"
- name: "component / Core (URLs)"
  color: "5319E7"
- name: "component / CSRF"
  color: "5319E7"
- name: "component / Database layer (models, ORM)"
  color: "5319E7"
- name: "component / Documentation"
  color: "5319E7"
- name: "component / Error reporting"
  color: "5319E7"
- name: "component / File uploads/storage"
  color: "5319E7"
- name: "component / Forms"
  color: "5319E7"
- name: "component / Generic views"
  color: "5319E7"
- name: "component / GIS"
  color: "5319E7"
- name: "component / HTTP handling"
  color: "5319E7"
- name: "component / Internationalization"
  color: "5319E7"
- name: "component / Migrations"
  color: "5319E7"
- name: "component / Packaging"
  color: "5319E7"
- name: "component / Template system"
  color: "5319E7"
- name: "component / Testing framework"
  color: "5319E7"
- name: "component / Utilities"
  color: "5319E7"
- name: "size / small"
  color: "C2E0C6"
- name: "size / medium"
  color: "C2E0C6"
- name: "size / large"
  color: "C2E0C6"
- name: "phase / new"
  color: "FBCA04"
- name: "phase / is there community support"
  color: "FBCA04"
- name: "phase / is this expected in core"
  color: "FBCA04"
- name: "phase / third-party package"
  color: "FBCA04"
- name: "phase / needs community DEP"
  color: "FBCA04"
- name: "phase / wontfix"
  color: "FBCA04"
- name: "phase / needs SC DEP"
  color: "FBCA04"
- name: "phase / implementation"
  color: "FBCA04"
- name: "type / commercial"
  color: "9F2EEB"
- name: "type / feature"
  color: "9F2EEB"
- name: "type / merge-package"
  color: "9F2EEB"