- name: "Django Core"
  color: "3FBE38"
  description: "This idea is suitable for inclusion in Django itself"
- name: "Third Party Package"
  color: "2898D8"
  description: "This idea is suitable for the third party package ecosystem"
- name: "Admin"
- name: "Async"
- name: "Authentication/Users"
- name: "Contributing to Django"
- name: "Documentation"
- name: "Frontend/JavaScript"
- name: "Forms"
- name: "GeoDjango"
- name: "Internationalization"
- name: "Middleware"
- name: "Migrations"
- name: "Models/ORM"
- name: "Rest APIs"
- name: "Templates"
- name: "Testing"
- name: "URLs"
- name: "Views"
