- name: "Django Core"
  color: "3FBE38"
  description: "This idea is suitable for inclusion in Django itself"
- name: "Third Party Package"
  color: "2898D8"
  description: "This idea is suitable for the third party package ecosystem"
- name: "Admin"
  color: "5319E7"
- name: "Async"
  color: "5319E7"
- name: "Authentication/Users"
  color: "5319E7"
- name: "Contributing to Django"
  color: "5319E7"
- name: "Documentation"
  color: "5319E7"
- name: "Frontend/JavaScript"
  color: "5319E7"
- name: "Forms"
  color: "5319E7"
- name: "GeoDjango"
  color: "5319E7"
- name: "Internationalization"
  color: "5319E7"
- name: "Middleware"
  color: "5319E7"
- name: "Migrations"
  color: "5319E7"
- name: "Models/ORM"
  color: "5319E7"
- name: "Rest APIs"
  color: "5319E7"
- name: "Templates"
  color: "5319E7"
- name: "Testing"
  color: "5319E7"
- name: "URLs"
  color: "5319E7"
- name: "Views"
  color: "5319E7"
