blank_issues_enabled: false
contact_links:
  - name: Django Security Issues
    url: https://docs.djangoproject.com/en/dev/internals/contributing/bugs-and-features/#reporting-security-issues
    about: Please report security vulnerabilities according to our security guidelines.
