---
name: Feature
description: Suggest a new feature or enhancement
labels: ['type / feature', 'phase / new']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking time to suggest your idea! Please be aware that this process takes a while (at least weeks). We appreciate your patience!

        If you haven't already, [please go search the existing issues for ideas similar to yours](https://github.com/django/new-features/issues?q=is%3Aissue).

        Please use a single issue for a one feature suggestions. If you have related ideas, please create multiple issues which reference each other.

        If English isn't your native language, let us know and do your best. If you'd like, you can answer in your native language and we'll use translation tools.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://www.djangoproject.com/conduct/)
      options:
        - label: I agree to follow Django's Code of Conduct
          required: true

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Describe your idea in a sentence or two.
      placeholder: A clear and concise description of what you'd like to see.
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem(s) does this solve? Please explain the problem or problems this feature would address.
    validations:
      required: true

  - type: dropdown
    id: request
    attributes:
      label: Request or proposal
      description: Do you propose being part of the team that will implement the feature or are you requesting for a feature to be built by others
      options:
        - request
        - proposal
    validations:
      required: true

  - type: textarea
    id: additional-details
    attributes:
      label: Additional Details
      description: Please share any other details you have. Please provide any additional context, screenshots, or examples that might help.
    validations:
      required: false

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Suggestions
      description: Can you share your suggestion(s) on how to implement this? This doesn't need to be the solution or even a POC. Sometimes it's easier for people to think about a feature when they can see part of the code.
    validations:
      required: false
